version: 2
jobs:
  build:
    working_directory: /mypy-mode
    docker:
      - image: serialdev/sdev-emacs
      # - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Check Emacs
          command: "emacs --version" 
      - run:
          name: Test docker image validity
          command: "https://raw.githubusercontent.com/cask/cask/master/go | python \
          make test" 


